### PR TITLE
Navigation drawer now with opacity 0.6

### LINKED ISSUE #37: Navigation drawer items are too prominent
**Describe the bug**

Use medium emphasis for non-selected navigation items

**Environment:**

- Device:  
- Device version:  
- App version:

### PR DESCRIPTION
**Pull request by DevSchmidtchen**
**Fixes: #37**

**Checklist**

- [x] Tested on actual devices
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Changes**

### CODE REVIEW

File: lib/onboarding/widgets/about_myself.dart [hunk 1]
```diff
@@ -217,12 +217,6 @@ class _InlineDropdownButton<T> extends StatelessWidget {
     final style = DefaultTextStyle.of(context).style;
 
     return DropdownButton(
-      selectedItemBuilder: (context) => items
-          .map((i) => DefaultTextStyle(
-                style: style,
-                child: i.child,
-              ))
-          .asList(),
```
Comment (MarcelGarus) [inline lib/onboarding/widgets/about_myself.dart:225]: You should probably leave that code, because removing it was just a temporary fix.

**Review by MarcelGarus — CHANGES_REQUESTED** [review]

**Review by MarcelGarus — APPROVED** [review]
