### PR TITLE
fix(tools): fix timer-related issues

### LINKED ISSUE #34: Timer counts negative values
**Describe the bug**

**Environment:**

- Device:  
- Device version:  
- App version:

### LINKED ISSUE #40: Add a sound when the timer elapses
**Description**

### PR DESCRIPTION
**Pull request by ctiedt**
**Fixes: #34**

Also fixes #40 

Merge #60 first

**Checklist**

- [x] Commit messages follow conventionalcommits.org
- [x] Tested on actual devices
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Changes**
The timer will not continue after time has elapsed anymore. The notification sound will play once the timer has elapsed. A custom sound could be added in the future.

### CODE REVIEW

File: lib/food/widgets/food_fragment.dart [hunk 1]
```diff
@@ -20,23 +21,30 @@ class FoodFragment extends StatelessWidget {
...
+        if (!snapshot.hasData) return buildLoadingError(snapshot);
+
+        if (snapshot.data.isEmpty()) {
+          return DashboardFragment(
+            title: Text(HpiL11n.get(context, 'food')),
+            child: Center(
+                child: Padding(
+              padding: const EdgeInsets.all(16.0),
+              child: Text(HpiL11n.get(context, 'food/noMenu')),
+            )),
```
Comment (MarcelGarus) [inline lib/food/widgets/food_fragment.dart]: A trailing comma makes for better code formatting. Also, we can merge the `Center` and `Padding` to a `Container` with `alignment` and `padding` set.

File: lib/food/widgets/menu_item.dart [hunk 2]
```diff
@@ -30,7 +36,7 @@ class MenuItemView extends StatelessWidget {
             SizedBox(
               width: 32,
               child: Text(
-                item.counter,
+                (showCounter) ? item.counter : ' ',
```
Comment (MarcelGarus) [inline lib/food/widgets/menu_item.dart]: No parenthesis needed here

File: lib/food/widgets/restaurant_menu.dart [hunk 3]
```diff
@@ -1,60 +1,50 @@
...
-                  ...menuItems.map((item) => MenuItemView(item)).iter,
-                ],
-              ),
-            ),
-          ),
+    return DashboardFragment(
+      title: StreamBuilder<Restaurant>(
+        stream: Provider.of<FoodBloc>(context).getRestaurant(restaurantId),
+        builder: (context, snapshot) => Text(
+          (snapshot.hasData)
```
Comment (MarcelGarus) [inline lib/food/widgets/restaurant_menu.dart]: Parenthesis not needed

**Review by MarcelGarus — CHANGES_REQUESTED** [review]

**Review by MarcelGarus — APPROVED** [review]
